#!/usr/bin/env bash
# Native equivalent of ruflo-loop-workers for the weekly trend scan.
#
# Cron this on any host where you keep this repo cloned:
#
#   0 9 * * 1   cd /path/to/extension1 && ./pipeline/loop-trend-scan.sh
#
# It does NOT call Claude Code (that requires an interactive session).
# It opens a stub trend-scan markdown file pre-filled with the prompt
# from pipeline/prompts/weekly-trend-scan.md, dated, ready to be
# filled by the next interactive session you run.
#
# The first time the workflow is mature enough, swap this to actually
# invoke `claude -p` (Claude Code in headless mode) with the prompt as
# input — but only after you trust the output.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATE="$(date +%Y-%m-%d)"
PROMPT_FILE="$ROOT/pipeline/prompts/weekly-trend-scan.md"

if [ ! -f "$PROMPT_FILE" ]; then
  echo "missing $PROMPT_FILE" >&2
  exit 1
fi

# Ensure both channels have a trend-scan stub for this Monday.
for channel in channel the-long-light; do
  out="$ROOT/$channel/trend-scan-$DATE.md"
  if [ -f "$out" ]; then
    echo "skip: $out already exists"
    continue
  fi
  {
    echo "# Trend scan — $channel — $DATE"
    echo
    echo "> Generated by pipeline/loop-trend-scan.sh."
    echo "> Run an interactive Claude Code session against this file's"
    echo "> prompt block to fill in the actual scan results."
    echo
    echo "## Prompt to run"
    echo
    sed -n '/^```$/,/^```$/p' "$PROMPT_FILE" | sed '1d;$d'
    echo
    echo "---"
    echo
    echo "## Findings (fill in)"
    echo
    echo "### 5–8 emerging themes"
    echo
    echo "### Top 2 video angles"
  } > "$out"
  echo "wrote: $out"
done

# Commit but don't push — leave it to the operator to review.
cd "$ROOT"
if git diff --cached --quiet && [ -z "$(git status --porcelain channel/trend-scan-$DATE.md the-long-light/trend-scan-$DATE.md 2>/dev/null)" ]; then
  echo "no new trend-scan stubs to commit"
  exit 0
fi
git add channel/trend-scan-$DATE.md the-long-light/trend-scan-$DATE.md 2>/dev/null || true
git commit -m "weekly trend scan stubs, $DATE" 2>/dev/null || echo "nothing to commit"
echo "done. push manually after review."
